### ISSUE TITLE
Vue public ne fonctionne pas

### ISSUE THREAD

**Issue by SebCanet** [ldleman/hackpoint#11]
Bonjour,
quoique je mette comme option en cliquant sur l'oeil, je n'ai pas de sketch visible hors authentification.
Merci.

**Comment by ldleman** [comment]
La mise en public d'un sketch rend ce sketch public sans authentification uniquement a partir de son url (qui doit ressembler à http://xxx/hackpoint/sketch.php?id=xxx) si tu tente d'afficher la liste des sketchs c'est normal que ça ne fonctionne pas.

Peux tu me confirmer que c'est bien le cas ?

**Comment by SebCanet** [comment]
Ah ok ! Je pensais voir une liste de skeetch apparaître hors connexion...
Ca serait sympa de pouvoir avoir lister ça pour les visiteurs.
Merci.

**Comment by ldleman** [comment]
Je suis d'accord et j'ai même un peu anticipé, j'ai fait cette modif hier, normalement c'est bon  :)

**Comment by SebCanet** [comment]
:-D merci.
