### ISSUE TITLE
Fonctionnalité lien des composants disparue

### ISSUE THREAD

**Issue by lademan** [ldleman/hackpoint#12]
Bonjour @ldleman 

Merci pour ce projet sympathique qui me permet de suivre mes bidouilles en cours.

La fonctionnalité d'ajout de lien au niveau des composants a disparue alors qu'elle fonctionnait bien.

J'ai l'impression que le merge du 15/08 a écrasé les modifications de @gmarsay ( cf issue #3 et bug #4 ).

Ou alors je n'ai rien compris à git, ce qui n'est pas exclu ;)

**Comment by ldleman** [comment]
Salut :)
De souvenir je l'avais supprimée car ça n'avait pas vraiment de sens de mettre un lien sur un composant, ceux ci changeant trop régulierement.

Comme la demande de remise du lien à été faite par pas mal de monde je viens de le remettre

**Comment by ldleman** [comment]
Je clos, n'hésite pas a rouvrir si besoin.
