### ISSUE TITLE
Légère amélioration graphique

### ISSUE THREAD

**Issue by valentin8709** [ldleman/hackpoint#13]
Salut Idle!
J'utilise assez régulièrement Hackpoint, et encore une fois, j'adore! Par contre, la page de login est vraiment pas folle... Serait-il possible d'avoir un truc un peu plus sympa? J'ai fais ça rapido (je ne suis pas développeur, c'est juste pour te montrer un exemple de login archi facile à faire et un poil plus sympathique).

![hackpoint](https://cloud.githubusercontent.com/assets/6785619/19201036/410d6f38-8ccc-11e6-9f2e-17670abddc86.png)

Merci bien =D

**Comment by ldleman** [comment]
fait :)
