### ISSUE TITLE
Compsants

### ISSUE THREAD

**Issue by Stephan35** [ldleman/hackpoint#15]
Bonjour,
Je commence à utiliser hackpoint pour mes projets.
Je souhaiterai rajouter une colonne lien (link to) dans la nomenclature faisant référence à un site d'achat.
L'utilisateur pourrais ainsi facilement retrouve le produit ... (si le lien existe toujours hi hi hi)

Merci pour vos explications (fichiers à modifier)

Grand merci pour hackpoint

**Comment by ldleman** [comment]
C'est fait :)
