### ISSUE TITLE
Images ne s'affichent pas et ne se téléchargent pas

### ISSUE THREAD

**Issue by SebCanet** [ldleman/hackpoint#19]
Bonjour,
en voici un exemple : [http://82.224.255.83:88/hackpoint/sketch.php?id=1#resource=6](http://82.224.255.83:88/hackpoint/sketch.php?id=1#resource=6)

Merci d'avance.

**Comment by ldleman** [comment]
Salut :),
Sympa le projet ! Ça fonctionne ?
Est ce que tu as une erreur particulière dans /var/logs/apache2/error.log au moment d'afficher/d'envoyer l'image ?

**Comment by SebCanet** [comment]
Oui, ça fonctionne, facile à mettre en place pour les élèves.
Je n'ai pas activé de SSH sur mon NAS...j'essaie de regarder ça.

**Comment by SebCanet** [comment]
A priori rien d'anormal, il ne m'indique pas de message d'erreur...

**Comment by ldleman** [comment]
Normalement c'est corrigé, tu peux réésayer ?

**Comment by SebCanet** [comment]
Nickel ! Merci beaucoup.
