### ISSUE TITLE
Les images s'uploadent bien mais ne s'affiche pas

### ISSUE THREAD

**Issue by valentin8709** [ldleman/hackpoint#20]
Salut Idleman!
J'espère que tout va bien pour toi. Cela fait un bout de temps que j'utilise hackpoint et je trouve ça toujours aussi génial =) Par contre, j'ai un bug qui apparaît depuis peu: les ressources images ne s'affichent plus. Je peux bien en créer une puis en uploader, mais cela m'affiche le logo d'une image cassée comme si hackpoint ne trouvait pas le fichier.

J'ai bien vérifié l'image est au bon endroit sur le serveur, je peux y accéder en tapant par exemple https://yana/hackpoint/upload/sketch/5.png et elle s'affiche correctement, les permissions sont aussi ok (644 sur les imgs, www-data comme owner). J'ai aussi essayé de désactiver la protection Firefox qui bloque le contenu http sur une page https, mais ce n'est pas ça.

Côté logs, voilà ce que j'ai:
`
[Sat Aug 26 11:59:34.483810 2017] [:error] [pid 30740] [client 192.168.1.148:52648] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'finfo_file(upload/sketch/38.png): failed to open stream: No such file or directory' in /var/www/hackpoint/action.php:471\nStack trace:\n#0 [internal function]: errorToException(2, 'finfo_file(uplo...', '/var/www/hackpo...', 471, Array)\n#1 /var/www/hackpoint/action.php(471): finfo_file(Resource id #1, 'upload/sketch/3...')\n#2 {main}\n  thrown in /var/www/hackpoint/action.php on line 471, referer: https://yana/hackpoint/sketch.php?id=3`

Voilà si tu as un peu de temps pour me dire où est-ce que j'aurai pu faire une bêtise!
Merci beaucoup!

**Comment by ldleman** [comment]
Fuck, voilà un bug que je pensais avoir push il y a longtemps ^^.
J'ai envoyé le correctif, désolé pour l'attente ça aurais du être push depuis plus d'un an oO !
Pour info le soucis ne viens pas d'une permission mais d'un espace et/ou d'un BOM d'encodage qui apparait sur toutes les pages, celui ci casse les flux fichiers, il me suffit de noettoyer le buffer avant génération du flux pour corriger le pb :).

**Comment by valentin8709** [comment]
Problème réglé! Merci pour ta réactivité et pour la petite explication =)

**Comment by ldleman** [comment]
Np :)
