### ISSUE TITLE
coloration syntaxique Arduino

### ISSUE THREAD

**Issue by SebCanet** [ldleman/hackpoint#22]
Est il possible d'améliorer la coloration syntaxique pour qu'il y ait plus de détails ?
Merci.

**Comment by ldleman** [comment]
Effectivement c'est pas jojo, j'ai ajouté un bloc de coloration avec les mots clés de l'ardui (faudra certainement vider ton cache)

**Comment by SebCanet** [comment]
C'est bien mieux, merci !
