### ISSUE TITLE
Un lien pour indiquer ou l'on a repéré le composant

### ISSUE THREAD

**Issue by nithir** [ldleman/hackpoint#3]
On peut indiquer son prix mais il serait aussi sympa de pouvoir associer un lien ou plusieurs vers des site marchant qui distribue le produit en question.

**Comment by gmarsay** [comment]
La possibilité d'ajouter un lien sur un composant existe déjà mais le champs "Lien" n'apparait pas dans le formulaire lors de l'ajout d'un composant. J'ai fait un pull request il y a quelques jours qui corrige ce bug : https://github.com/ldleman/hackpoint/pull/4
En attente d'intégration par @ldleman

**Comment by ldleman** [comment]
C'est intégré :), merci pour les modifs
