### ISSUE TITLE
Filtrage des images pour les composants?

### ISSUE THREAD

**Issue by valentin8709** [ldleman/hackpoint#5]
Salut Idle!
Après avoir ajouté tous mes petits composants, j'essaye d'uploader une image correspondante pour chacune mais ça ne marche pas (pas de msg d'erreur au passage). Est-ce qu'il y a des conditions particulières pour l'upload? L'image que j'ai testé est en .jpg en 800x800.

Merci pour tout =)

**Comment by ldleman** [comment]
Nop normalement le jpg passe, vérifie que ton repertoire est bien réglé en écriture, au pire remet apache en proprio sur tous le dossier
`chown -R www-data:www-data /var/www/chemin/vers/hackpoint`

**Comment by valentin8709** [comment]
Fait! Mais ça ne fonctionne pas... j'ai vérifié les droits du dossiers "upload" et tout est bon. D'ailleurs quand je crée une ressource "image", le contenu est bien uploadé et tout fonctionne correctement. Mais pas pour les composants...

**Comment by ldleman** [comment]
J'arrive a reproduire mais ça n'arrive que lorsque j’envoie de grosses images genre plus de 2mo, ça te fait la même chose ?

**Comment by ldleman** [comment]
Je pense avoir trouvé le pb, ta configuration php n'autorise pas les fichier supérieurs a "x" mo (définit dans ton php.ini), il te faut augmenter cette valeur si tu veux pouvoir blancer un gros fichier.
Les valeurs a modifier sont 
upload_max_filesize = ... et post_max_size = ... dans ton fichier php.ini

**Comment by valentin8709** [comment]
Bon j'ai mis à jour les fichiers apache/php.ini et cli/php.ini (jamais compris pourquoi y'en avait deux mais bon) en mettant 200Mo pour les paramètres que tu m'as filé, j'ai désactivé le SSL (firefox refuse parfois d'upload en http sur un site en https), j'ai resize l'image en 50x50 px qui pèse maintenant 4ko, et le mystère reste entier...

Un peu de log si ça peut aider éventuellement:

**access.log:**

```
192.168.1.254 - - [06/Jun/2016:17:11:58 +0200] "POST /hackpoint/action.php HTTP/1.1" 200 471 "http://valou.noip.me:8081/hackpoint/component.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:46.0) Gecko/20100101 Firefox/46.0"
192.168.1.254 - - [06/Jun/2016:17:11:58 +0200] "GET /hackpoint/img/default_image.png?t=1465225918 HTTP/1.1" 200 1338 "http://XXXX:YYYY/hackpoint/component.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:46.0) Gecko/20100101 Firefox/46.0"
192.168.1.254 - - [06/Jun/2016:17:12:04 +0200] "POST /hackpoint/action.php?action=upload_component_image HTTP/1.1" 500 324 "http://XXXX:YYYY/hackpoint/component.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:46.0) Gecko/20100101 Firefox/46.0"
::1 - - [06/Jun/2016:17:12:04 +0200] "OPTIONS * HTTP/1.0" 200 128 "-" "Apache/2.4.10 (Raspbian) OpenSSL/1.0.1k (internal dummy connection)"
192.168.1.254 - - [06/Jun/2016:17:12:07 +0200] "POST /hackpoint/action.php HTTP/1.1" 200 441 "http://XXXX:YYYY/hackpoint/component.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:46.0) Gecko/20100101 Firefox/46.0"
192.168.1.254 - - [06/Jun/2016:17:12:07 +0200] "POST /hackpoint/action.php HTTP/1.1" 200 1594 "http://XXXX:YYYY/hackpoint/component.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:46.0) Gecko/20100101 Firefox/46.0"
```

**error.log**

```
[Mon Jun 06 17:11:46.723951 2016] [:error] [pid 17732] [client 192.168.1.254:53669] PHP Fatal error:  Call to undefined function imagecreatefromstring() in /var/www/hackpoint/function.php on line 154, referer: https://XXXX:YYYY/hackpoint/component.php
[Mon Jun 06 17:12:04.102831 2016] [:error] [pid 17736] [client 192.168.1.254:53684] PHP Fatal error:  Call to undefined function imagecreatefromstring() in /var/www/hackpoint/function.php on line 154, referer: http://XXXX:YYYY/hackpoint/component.php
```

Apparemment tu utilises une fonction non déclarée, mais bon je sais pas d'où ça vient... Et pour info j'ai fais un git pull tout frais pour être sûr d'avoir la dernière version.

**Comment by gmarsay** [comment]
> [Mon Jun 06 17:11:46.723951 2016] [:error] [pid 17732] [client 192.168.1.254:53669] PHP Fatal error:  Call to undefined function imagecreatefromstring() in /var/www/hackpoint/function.php on line 154, referer: https://XXXX:YYYY/hackpoint/component.php
> [Mon Jun 06 17:12:04.102831 2016] [:error] [pid 17736] [client 192.168.1.254:53684] PHP Fatal error:  Call to undefined function imagecreatefromstring() in /var/www/hackpoint/function.php on line 154, referer: http://XXXX:YYYY/hackpoint/component.php

Ces messages indiquent que l'extension GD de PHP n'est pas installée : 
- sous Linux (Debian/Ubuntu) `apt-get install php5-gd` et relancer Apache `/etc/init.d/apache2 restart`
- sous WAMP : WAMP > PHP > PHP extensions > cocher "php_gd2"

**Comment by valentin8709** [comment]
Bien vu! Merci bien =) alors maintenant j'arrive à glisser l'image sur le site, qui s'affiche correctement, mais lorsque je clique sur "enregistrer" j'ai le message suivant qui s'affiche:

```
ERREUR : 
fopen(upload/part/1.png): failed to open stream: No such file or directory 
  /var/www/hackpoint/function.php - L 46
```

Pour résoudre le problème, j'ai simplement crée le répertoire hackpoint/upload/part/
Maintenant tout fonctionne =) Mais ce serait peut être cool de balancer les dépendances et la création du répertoire à l'installe ou dans un readme ou quoi qu'est-ce =)

**Comment by ldleman** [comment]
Oaip je m'occupe de tout ça, c'est vrai que j'ai pas assez chiadé l'installation :)

**Comment by ldleman** [comment]
C'est fait :), ajout d'un readme avec les pré-requis + vérification a l'install
